require "rbconfig"
require "bundler/gem_tasks"
require "rake/testtask"

desc 'Preventative work'
task :tidy_up do
  sh 'cargo clean'
end

desc 'Build Rust extension'
task :compile do
  case RbConfig::CONFIG['host_os']
  when /darwin|mac os/
    sh 'cargo rustc --release -- -C link-args=-Wl,-undefined,dynamic_lookup'
  else
    sh 'cargo build --release'
  end
end

desc 'bundle install'
task :bundle_install do
  sh 'bundle install'
end

Rake::TestTask.new(test: [:tidy_up, :bundle_install, :compile]) do |t|
  t.libs << "test"
  t.libs << "lib"
  t.test_files = FileList["test/**/*_test.rb"]
end

task :default => :test
